/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.darkem.poo;

/**
 *
 * @author emmanuel
 */
import java.awt.Color;

/**
 *
 * @author zapte
 */
public class Mavenproject1 extends javax.swing.JFrame {

    public Mavenproject1() {
        initComponents();
        //Image icon = new ImageIcon(getClass().getResource("/com/darkem/poo/images/Buho.jpg")).getImage();
        //this.setIconImage(icon);
        setLocationRelativeTo(null); //Centre el formulario 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LblImagen = new javax.swing.JLabel();
        Lblcarga = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 95));
        setUndecorated(true);

        LblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/darkem/poo/images/logo.jpeg"))); // NOI18N

        ProgressBar.setBackground(new java.awt.Color(34, 133, 225));
        ProgressBar.setForeground(new java.awt.Color(209, 209, 209));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lblcarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(LblImagen)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblImagen)
                .addGap(18, 18, 18)
                .addComponent(Lblcarga, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    Mavenproject1 splash = new Mavenproject1(); //inicializamos 
    splash.setVisible (true);
    try{
        for(int i=0; i<=100; i++){
            Thread.sleep(35);
            splash.ProgressBar.setValue(i);
            splash.ProgressBar.setBackground(Color.white);
            splash.ProgressBar.setForeground(Color.blue);
            splash.Lblcarga.setText("Cargando sistema, espere por favor..." + (Integer.toString(i)+"%"));
            if (i == 100){
                splash.setVisible(false);
                TutorialFrame frame = new TutorialFrame();
            }
        }
    }catch (Exception e){
        
    }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel LblImagen;
    private javax.swing.JLabel Lblcarga;
    private javax.swing.JProgressBar ProgressBar;
    // End of variables declaration                   
}